version: '3'

services:
  server:
    image: docker.io/bitnami/mongodb:7.0
    container_name: mongodb
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type == database
    environment:
      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGODB_ROOT_USER=$MONGODB_ROOT_USER
    ports:
      - 27017:27017
    networks:
      database:
        ipv4_address: 172.20.0.5
    volumes:
      - mongodb_data:/bitnami/mongodb

networks:
  database:
    external: true
volumes:
  mongodb_data:
    external: true