version: '3'

services:
    server:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql
    restart: always
    deploy:
        mode: replicated
        replicas: 1
        placement:
        constraints:
            - node.labels.type == database
    ports:
        - 3306:3306
    volumes:
        - mysql_data:/bitnami/mysql/data
    environment:
        - MYSQL_ROOT_PASSWORD=gqf.VKJ.utq6npc-fzr
      - MYSQL_ROOT_USER=zpm.root
    networks:
        database:
        ipv4_address: 172.20.0.2

networks:
    database:
    external: true

volumes:
    mysql_data:
    external: true