version: '3'

services:
  server:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
      constraints:
        - node.labels.type == database
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_USER=$MYSQL_ROOT_USER
    ports:
      - 3306:3306
    networks:
      database:
        ipv4_address: 172.20.0.2
    volumes:
        - mysql_data:/bitnami/mysql/data

networks:
  database:
    external: true

volumes:
  mysql_data:
    external: true